import json
import time
from typing import List, Dict, Any, Optional
from pathlib import Path
from dataclasses import dataclass, field


@dataclass
class Account:
    """Account information (descriptive)"""
    account_id: str  # Unique identifier
    login_task_description: str  # Login task description (e.g. "Log in with username admin and password 123456")
    role: str = "user"  # Role label
    is_logged_in: bool = False
    credentials: Dict[str, Any] = field(default_factory=dict)  # {cookies, headers, localStorage, sessionStorage}
    login_url: Optional[str] = None
    created_at: float = field(default_factory=time.time)
    has_driver: bool = False  # Whether there is an associated driver (for identification)


class AccountManager:
    """
    Account Manager - Descriptive version

    Core improvements:
    1. No longer hardcodes username/password fields
    2. Uses login_task_description to pass login information
    3. Lets Bridge/LLM decide how to fill in forms
    4. Supports storing and managing WebDriver instances (for scenarios requiring JS execution like XSS)
    """

    def __init__(self, store_path: str = "output/accounts.json", chrome_options=None, default_login_url: str = None):
        self.store_path = Path(store_path)
        self.accounts: List[Account] = []
        self.chrome_options = chrome_options
        self.default_login_url = default_login_url  # Save default login URL

        # Driver storage (account_id -> WebDriver instance)
        # Note: driver will not be serialized to JSON, only exists at runtime
        self._drivers: Dict[str, Any] = {}

        # Load stored accounts
        self._load_accounts()

    def add_account(self,
                   login_task_description: str,
                   role: str = "user",
                   account_id: Optional[str] = None) -> Account:
        """
        Add account (descriptive)

        Args:
            login_task_description: Login task description, e.g.:
                "Log in with username: admin, password: admin123"
                "Log in with email test@example.com and password Pass@123"
            role: Role label (for classification)
            account_id: Optional account ID (auto-generated by default)

        Returns:
            The created Account object
        """
        if account_id is None:
            account_id = f"account_{int(time.time())}_{len(self.accounts)}"

        account = Account(
            account_id=account_id,
            login_task_description=login_task_description,
            role=role
        )

        self.accounts.append(account)
        self.save_accounts()

        return account

    def login_account(self,
                 account: Account,
                 login_url: str = None,  # Changed to optional parameter
                 bridge = None) -> bool:
        """
        Execute account login

        Args:
            account: The account to log in
            login_url: Login page URL (optional, defaults to the URL passed during initialization)
            bridge: Bridge instance

        Returns:
            Whether login was successful
        """
        from task.tasks import Task

        # Use the provided URL or default URL
        if login_url is None:
            login_url = self.default_login_url

        if not login_url:
            raise ValueError("No login URL provided and no default login URL set")

        print(f"[AccountManager] Logging in account: {account.account_id}")
        print(f"  Task: {account.login_task_description}")
        print(f"  URL: {login_url}")

        # Create login task
        login_task = Task(
            task_id=f"login_{account.account_id}",
            description=account.login_task_description,
            initial_url=login_url
        )

        # Navigate to login page
        bridge.driver.get(login_url)
        time.sleep(0.6)

        # Execute login
        try:
            bridge.run_task(login_task,
                        photo_dir=Path("output/account_logins") / account.account_id,
                        logging_in=True)

            # Extract credentials
            time.sleep(1)
            credentials = self._extract_credentials(bridge.driver)

            # Save driver instance
            self._drivers[account.account_id] = bridge.driver

            # Update account state
            account.credentials = credentials
            account.is_logged_in = True
            account.login_url = login_url
            account.has_driver = True  # Mark as having a driver

            self.save_accounts()

            print(f"[AccountManager] Login successful")
            return True

        except Exception as e:
            print(f"[AccountManager] Login failed: {e}")
            return False

    def _extract_credentials(self, driver) -> Dict[str, Any]:
        """
        Extract credentials from driver (full version, no filtering)

        Returns:
            {
                "cookies": [...],
                "localStorage": {...},
                "sessionStorage": {...},
                "headers": {}  # Empty for now, attack Agent decides what to use
            }
        """
        print(f"[DEBUG] Starting credential extraction...")
        print(f"[DEBUG] Current URL: {driver.current_url}")

        # # Extract cookies (usually no issues)
        # try:
        #     cookies = driver.get_cookies()
        #     print(f"[DEBUG] Cookies extraction successful: {len(cookies)} cookies")
        # except Exception as e:
        #     print(f"[DEBUG] Cookies extraction failed: {e}")
        #     cookies = []

        # ==========================================
        # Fix: Use official execute_cdp_cmd method
        # ==========================================
        cookies = []
        try:
            # Network.getAllCookies is a native Chrome DevTools command
            # It can bypass Path and Domain restrictions to get all cookies in the browser
            result = driver.execute_cdp_cmd('Network.getAllCookies', {})
            cookies = result.get('cookies', [])
            print(f"[DEBUG] (CDP) Cookies extraction successful: {len(cookies)} cookies")

            # Debug: Check if JSESSIONID exists
            for c in cookies:
                if 'SESSION' in c['name'].upper():
                    print(f"  Captured key Cookie: {c['name']} = {c['value'][:10]}... (Path: {c['path']})")

        except Exception as e:
            print(f"[DEBUG] CDP Cookie extraction failed, falling back to standard method: {e}")
            try:
                cookies = driver.get_cookies()
                print(f"[DEBUG] (Standard) Cookies extraction successful: {len(cookies)} cookies")
            except Exception as e2:
                print(f"[DEBUG] All Cookie extraction methods failed: {e2}")
                cookies = []

        # localStorage detailed diagnostics
        print(f"[DEBUG] Starting localStorage analysis...")

        # Step 1: Check localStorage basic info
        try:
            basic_info = driver.execute_script("""
                return {
                    length: localStorage.length,
                    url: window.location.href,
                    userAgent: navigator.userAgent.substring(0, 50)
                };
            """)
            print(f"[DEBUG] localStorage basic info: {basic_info}")
        except Exception as e:
            print(f"[DEBUG] Failed to get localStorage basic info: {e}")

        # Step 2: Calculate localStorage size
        try:
            size_info = driver.execute_script("""
                let totalSize = 0;
                let keyCount = 0;
                let largestKey = '';
                let largestSize = 0;

                for (let i = 0; i < localStorage.length; i++) {
                    const key = localStorage.key(i);
                    const value = localStorage.getItem(key);
                    const size = new Blob([key + value]).size;
                    totalSize += size;
                    keyCount++;

                    if (size > largestSize) {
                        largestSize = size;
                        largestKey = key;
                    }
                }

                return {
                    keyCount: keyCount,
                    totalSizeBytes: totalSize,
                    totalSizeKB: Math.round(totalSize / 1024 * 100) / 100,
                    largestKey: largestKey,
                    largestSizeBytes: largestSize,
                    largestSizeKB: Math.round(largestSize / 1024 * 100) / 100
                };
            """)
            print(f"[DEBUG] localStorage size analysis:")
            print(f"  - Key-value pairs: {size_info['keyCount']}")
            print(f"  - Total size: {size_info['totalSizeKB']} KB ({size_info['totalSizeBytes']} bytes)")
            print(f"  - Largest key: {size_info['largestKey']} ({size_info['largestSizeKB']} KB)")

            # Warning for large data
            if size_info['totalSizeKB'] > 100:
                print(f"[DEBUG] localStorage data is large (>100KB), may cause deserialization failure")

        except Exception as e:
            print(f"[DEBUG] Failed to calculate localStorage size: {e}")

        # Step 3: Try to get all key names (without values)
        try:
            keys_only = driver.execute_script("""
                const keys = [];
                for (let i = 0; i < localStorage.length; i++) {
                    keys.push(localStorage.key(i));
                }
                return keys;
            """)
            print(f"[DEBUG] localStorage key list: {keys_only}")
            print(f"[DEBUG] Number of keys: {len(keys_only)}")
        except Exception as e:
            print(f"[DEBUG] Failed to get localStorage key names: {e}")

        # Step 4: Try full extraction (original logic)
        print(f"[DEBUG] Attempting full localStorage extraction...")
        try:
            localStorage = driver.execute_script("""
                console.log('Starting localStorage extraction, item count:', localStorage.length);
                const out = {};
                for (let i = 0; i < localStorage.length; i++) {
                    const k = localStorage.key(i);
                    const v = localStorage.getItem(k);
                    out[k] = v;
                    console.log(`Extracting key ${i}: ${k.substring(0, 20)}... (length: ${v.length})`);
                }
                console.log('localStorage extraction complete, return object size:', JSON.stringify(out).length);
                return out;
            """)
            print(f"[DEBUG] localStorage full extraction successful: {len(localStorage)} items")

        except Exception as e:
            print(f"[DEBUG] localStorage full extraction failed: {e}")
            print(f"[DEBUG] Error type: {type(e).__name__}")
            print(f"[DEBUG] Error message: {str(e)}")
            localStorage = {}

            # Step 5: Try extracting one by one to find problematic keys
            print(f"[DEBUG] Attempting to extract localStorage items one by one...")
            try:
                keys = driver.execute_script("return Array.from({length: localStorage.length}, (_, i) => localStorage.key(i));")
                problem_keys = []

                for key in keys[:10]:  # Only check first 10
                    try:
                        value = driver.execute_script(f"return localStorage.getItem('{key}');")
                        print(f"[DEBUG] Key '{key[:30]}...' extraction successful (length: {len(value) if value else 0})")
                    except Exception as e:
                        print(f"[DEBUG] Key '{key[:30]}...' extraction failed: {e}")
                        problem_keys.append(key)

                if problem_keys:
                    print(f"[DEBUG] Found problematic keys: {problem_keys}")

            except Exception as e:
                print(f"[DEBUG] One-by-one extraction also failed: {e}")

        # sessionStorage similar diagnostics
        print(f"[DEBUG] Starting sessionStorage analysis...")
        try:
            session_size_info = driver.execute_script("""
                let totalSize = 0;
                for (let i = 0; i < sessionStorage.length; i++) {
                    const key = sessionStorage.key(i);
                    const value = sessionStorage.getItem(key);
                    totalSize += new Blob([key + value]).size;
                }
                return {
                    keyCount: sessionStorage.length,
                    totalSizeKB: Math.round(totalSize / 1024 * 100) / 100
                };
            """)
            print(f"[DEBUG] sessionStorage: {session_size_info['keyCount']} items, {session_size_info['totalSizeKB']} KB")
        except Exception as e:
            print(f"[DEBUG] sessionStorage size analysis failed: {e}")

        # Extract sessionStorage
        try:
            sessionStorage = driver.execute_script("""
                const out = {};
                for (let i = 0; i < sessionStorage.length; i++) {
                    const k = sessionStorage.key(i);
                    out[k] = sessionStorage.getItem(k);
                }
                return out;
            """)
            print(f"[DEBUG] sessionStorage extraction successful: {len(sessionStorage)} items")
        except Exception as e:
            print(f"[DEBUG] sessionStorage extraction failed: {e}")
            sessionStorage = {}

        print(f"[DEBUG] Credential extraction complete")

        credentials = {
            "cookies": cookies,
            "localStorage": localStorage,
            "sessionStorage": sessionStorage,
            "headers": {}  # No longer auto-extract Authorization
        }

        return credentials

    def get_credentials(self, account_identifier: str) -> Optional[Dict[str, Any]]:
        """
        Get account credentials

        Args:
            account_identifier: Account ID or role name (e.g. "admin", "user1")
                              Special value: "unauthenticated" returns empty credentials

        Returns:
            Credentials dictionary or None
        """
        if account_identifier == "unauthenticated":
            return {"cookies": [], "headers": {}, "localStorage": {}, "sessionStorage": {}}

        # Search by ID first
        for account in self.accounts:
            if account.account_id == account_identifier and account.is_logged_in:
                return account.credentials

        # Then search by role
        for account in self.accounts:
            if account.role == account_identifier and account.is_logged_in:
                return account.credentials

        return None

    def get_driver(self, account_identifier: str) -> Optional[Any]:
        """
        Get the WebDriver instance associated with the account

        Args:
            account_identifier: Account ID or role name

        Returns:
            WebDriver instance or None
        """
        # Search by ID first
        for account in self.accounts:
            if account.account_id == account_identifier and account.has_driver:
                return self._drivers.get(account.account_id)

        # Then search by role
        for account in self.accounts:
            if account.role == account_identifier and account.has_driver:
                return self._drivers.get(account.account_id)

        return None

    def set_driver(self, account_identifier: str, driver: Any) -> bool:
        """
        Set WebDriver instance for an account

        Args:
            account_identifier: Account ID
            driver: WebDriver instance

        Returns:
            Whether the setting was successful
        """
        for account in self.accounts:
            if account.account_id == account_identifier:
                self._drivers[account.account_id] = driver
                account.has_driver = True
                self.save_accounts()
                return True

        return False

    def has_driver(self, account_identifier: str) -> bool:
        """
        Check if the account has an available Driver

        Args:
            account_identifier: Account ID or role name

        Returns:
            Whether a driver exists
        """
        driver = self.get_driver(account_identifier)
        if driver is None:
            return False

        # Check if the driver is still valid
        try:
            _ = driver.current_url
            return True
        except Exception:
            # Driver is no longer valid, clean up
            for account in self.accounts:
                if account.account_id == account_identifier or account.role == account_identifier:
                    if account.account_id in self._drivers:
                        del self._drivers[account.account_id]
                    account.has_driver = False
                    self.save_accounts()
            return False

    def list_accounts(self) -> List[Account]:
        """Return all accounts"""
        return self.accounts

    def create_account_from_credentials(self,
                                       account_id: str,
                                       credentials: Dict[str, Any],
                                       role: str = "dynamic_user",
                                       login_url: Optional[str] = None) -> Account:
        """
        Create account directly from credentials (for dynamic login scenarios)

        Args:
            account_id: Account ID
            credentials: Credentials dictionary (containing cookies, headers, etc.)
            role: Role label
            login_url: Login URL (optional)

        Returns:
            The created Account object
        """
        # Check if account already exists
        for acc in self.accounts:
            if acc.account_id == account_id:
                # Update existing account
                acc.credentials = credentials
                acc.is_logged_in = True
                acc.login_url = login_url or acc.login_url
                acc.role = role
                self.save_accounts()
                print(f"[AccountManager] Updated existing account: {account_id}")
                return acc

        # Create new account
        account = Account(
            account_id=account_id,
            login_task_description=f"Dynamically created account {account_id}",
            role=role,
            is_logged_in=True,
            credentials=credentials,
            login_url=login_url
        )

        self.accounts.append(account)
        self.save_accounts()

        print(f"[AccountManager] Created new account: {account_id}")
        return account

    def format_for_prompt(self) -> str:
        """
        Format account information for LLM prompt

        Returns:
            Formatted string, e.g.:
            Available Accounts:
            1. admin (role: admin, logged_in: True)
               Task: Log in with username: admin, password: admin123
            2. user1 (role: user, logged_in: True)
               Task: Log in with username: testuser, password: test123
            3. unauthenticated (no credentials)
        """
        if not self.accounts:
            return "Available Accounts:\n- unauthenticated (no credentials)"

        lines = ["Available Accounts:"]
        for i, account in enumerate(self.accounts, 1):
            status = "logged_in: True" if account.is_logged_in else "logged_in: False"
            lines.append(f"{i}. {account.account_id} (role: {account.role}, {status})")
            lines.append(f"   Task: {account.login_task_description}")

        lines.append("- unauthenticated (no credentials)")

        return "\n".join(lines)

    def save_accounts(self):
        """Save account information to JSON"""
        self.store_path.parent.mkdir(parents=True, exist_ok=True)

        data = []
        for account in self.accounts:
            data.append({
                "account_id": account.account_id,
                "login_task_description": account.login_task_description,
                "role": account.role,
                "is_logged_in": account.is_logged_in,
                "credentials": account.credentials,
                "login_url": account.login_url,
                "created_at": account.created_at,
                "has_driver": account.has_driver  # Save driver flag
            })

        with open(self.store_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    def _load_accounts(self):
        """Load account information from JSON"""
        if not self.store_path.exists():
            return

        try:
            with open(self.store_path, 'r', encoding='utf-8') as f:
                data = json.load(f)

            for item in data:
                account = Account(
                    account_id=item["account_id"],
                    login_task_description=item["login_task_description"],
                    role=item.get("role", "user"),
                    is_logged_in=item.get("is_logged_in", False),
                    credentials=item.get("credentials", {}),
                    login_url=item.get("login_url"),
                    created_at=item.get("created_at", time.time()),
                    has_driver=item.get("has_driver", False)  # Load driver flag
                )
                self.accounts.append(account)

        except Exception as e:
            print(f"[AccountManager] Warning: Failed to load accounts: {e}")







