import json
import time
from typing import List, Dict, Any, Optional
from pathlib import Path
from dataclasses import dataclass, field


@dataclass
class Account:
    """Account information (descriptive)"""
    account_id: str  # Unique identifier
    login_task_description: str  # Login task description (e.g. "Log in with username admin and password 123456")
    role: str = "user"  # Role label
    is_logged_in: bool = False
    credentials: Dict[str, Any] = field(default_factory=dict)  # {cookies, headers, localStorage, sessionStorage}
    login_url: Optional[str] = None
    created_at: float = field(default_factory=time.time)
    has_driver: bool = False  # Whether there is an associated driver (for identification)


class AccountManager:
    """
    Account Manager - Descriptive version

    Core improvements:
    1. No longer hardcodes username/password fields
    2. Uses login_task_description to pass login information
    3. Lets InteractionExecutionAgent/LLM decide how to fill in forms
    4. Supports storing and managing WebDriver instances (for scenarios requiring JS execution like XSS)
    """

    def __init__(self, store_path: str = "output/accounts.json", chrome_options=None, default_login_url: str = None):
        self.store_path = Path(store_path)
        self.accounts: List[Account] = []
        self.chrome_options = chrome_options
        self.default_login_url = default_login_url  # Save default login URL

        # Driver storage (account_id -> WebDriver instance)
        # Note: driver will not be serialized to JSON, only exists at runtime
        self._drivers: Dict[str, Any] = {}

        # Load stored accounts
        self._load_accounts()

    def add_account(self,
                   login_task_description: str,
                   role: str = "user",
                   account_id: Optional[str] = None) -> Account:
        """
        Add account (descriptive)

        Args:
            login_task_description: Login task description, e.g.:
                "Log in with username: admin, password: admin123"
                "Log in with email test@example.com and password Pass@123"
            role: Role label (for classification)
            account_id: Optional account ID (auto-generated by default)

        Returns:
            The created Account object
        """
        if account_id is None:
            account_id = f"account_{int(time.time())}_{len(self.accounts)}"

        account = Account(
            account_id=account_id,
            login_task_description=login_task_description,
            role=role
        )

        self.accounts.append(account)
        self.save_accounts()

        return account

    def _extract_credentials(self, driver) -> Dict[str, Any]:
        """
        Extract credentials from driver (full version, no filtering)

        Returns:
            {
                "cookies": [...],
                "localStorage": {...},
                "sessionStorage": {...},
                "headers": {}  # Empty for now, attack Agent decides what to use
            }
        """
        # ==========================================
        # Fix: Use official execute_cdp_cmd method
        # ==========================================
        cookies = []
        try:
            # Network.getAllCookies is a native Chrome DevTools command
            # It can bypass Path and Domain restrictions to get all cookies in the browser
            result = driver.execute_cdp_cmd('Network.getAllCookies', {})
            cookies = result.get('cookies', [])

            # Check if session-related cookies exist
            for c in cookies:
                if 'SESSION' in c['name'].upper():
                    print(f"  Captured key Cookie: {c['name']} = {c['value'][:10]}... (Path: {c['path']})")

        except Exception as e:
            try:
                cookies = driver.get_cookies()
            except Exception as e2:
                cookies = []

        # Extract localStorage
        try:
            localStorage = driver.execute_script("""
                const out = {};
                for (let i = 0; i < localStorage.length; i++) {
                    const k = localStorage.key(i);
                    const v = localStorage.getItem(k);
                    out[k] = v;
                }
                return out;
            """)

        except Exception as e:
            localStorage = {}

            # Try extracting one by one to find problematic keys
            try:
                keys = driver.execute_script("return Array.from({length: localStorage.length}, (_, i) => localStorage.key(i));")

                for key in keys[:10]:  # Only check first 10
                    try:
                        value = driver.execute_script(f"return localStorage.getItem('{key}');")
                    except Exception as e:
                        pass

            except Exception as e:
                pass

        # Extract sessionStorage
        try:
            sessionStorage = driver.execute_script("""
                const out = {};
                for (let i = 0; i < sessionStorage.length; i++) {
                    const k = sessionStorage.key(i);
                    out[k] = sessionStorage.getItem(k);
                }
                return out;
            """)
        except Exception as e:
            sessionStorage = {}

        credentials = {
            "cookies": cookies,
            "localStorage": localStorage,
            "sessionStorage": sessionStorage,
            "headers": {}  # No longer auto-extract Authorization
        }

        return credentials

    def get_credentials(self, account_identifier: str) -> Optional[Dict[str, Any]]:
        """
        Get account credentials

        Args:
            account_identifier: Account ID or role name (e.g. "admin", "user1")
                              Special value: "unauthenticated" returns empty credentials

        Returns:
            Credentials dictionary or None
        """
        if account_identifier == "unauthenticated":
            return {"cookies": [], "headers": {}, "localStorage": {}, "sessionStorage": {}}

        # Search by ID first
        for account in self.accounts:
            if account.account_id == account_identifier and account.is_logged_in:
                return account.credentials

        # Then search by role
        for account in self.accounts:
            if account.role == account_identifier and account.is_logged_in:
                return account.credentials

        return None

    def get_driver(self, account_identifier: str) -> Optional[Any]:
        """
        Get the WebDriver instance associated with the account

        Args:
            account_identifier: Account ID or role name

        Returns:
            WebDriver instance or None
        """
        # Search by ID first
        for account in self.accounts:
            if account.account_id == account_identifier and account.has_driver:
                return self._drivers.get(account.account_id)

        # Then search by role
        for account in self.accounts:
            if account.role == account_identifier and account.has_driver:
                return self._drivers.get(account.account_id)

        return None

    def set_driver(self, account_identifier: str, driver: Any) -> bool:
        """
        Set WebDriver instance for an account

        Args:
            account_identifier: Account ID
            driver: WebDriver instance

        Returns:
            Whether the setting was successful
        """
        for account in self.accounts:
            if account.account_id == account_identifier:
                self._drivers[account.account_id] = driver
                account.has_driver = True
                self.save_accounts()
                return True

        return False

    def has_driver(self, account_identifier: str) -> bool:
        """
        Check if the account has an available Driver

        Args:
            account_identifier: Account ID or role name

        Returns:
            Whether a driver exists
        """
        driver = self.get_driver(account_identifier)
        if driver is None:
            return False

        # Check if the driver is still valid
        try:
            _ = driver.current_url
            return True
        except Exception:
            # Driver is no longer valid, clean up
            for account in self.accounts:
                if account.account_id == account_identifier or account.role == account_identifier:
                    if account.account_id in self._drivers:
                        del self._drivers[account.account_id]
                    account.has_driver = False
                    self.save_accounts()
            return False

    def list_accounts(self) -> List[Account]:
        """Return all accounts"""
        return self.accounts

    def create_account_from_credentials(self,
                                       account_id: str,
                                       credentials: Dict[str, Any],
                                       role: str = "dynamic_user",
                                       login_url: Optional[str] = None) -> Account:
        """
        Create account directly from credentials (for dynamic login scenarios)

        Args:
            account_id: Account ID
            credentials: Credentials dictionary (containing cookies, headers, etc.)
            role: Role label
            login_url: Login URL (optional)

        Returns:
            The created Account object
        """
        # Check if account already exists
        for acc in self.accounts:
            if acc.account_id == account_id:
                # Update existing account
                acc.credentials = credentials
                acc.is_logged_in = True
                acc.login_url = login_url or acc.login_url
                acc.role = role
                self.save_accounts()
                print(f"[AccountManager] Updated existing account: {account_id}")
                return acc

        # Create new account
        account = Account(
            account_id=account_id,
            login_task_description=f"Dynamically created account {account_id}",
            role=role,
            is_logged_in=True,
            credentials=credentials,
            login_url=login_url
        )

        self.accounts.append(account)
        self.save_accounts()

        print(f"[AccountManager] Created new account: {account_id}")
        return account

    def format_for_prompt(self) -> str:
        """
        Format account information for LLM prompt

        Returns:
            Formatted string, e.g.:
            Available Accounts:
            1. admin (role: admin, logged_in: True)
               Task: Log in with username: admin, password: admin123
            2. user1 (role: user, logged_in: True)
               Task: Log in with username: testuser, password: test123
            3. unauthenticated (no credentials)
        """
        if not self.accounts:
            return "Available Accounts:\n- unauthenticated (no credentials)"

        lines = ["Available Accounts:"]
        for i, account in enumerate(self.accounts, 1):
            status = "logged_in: True" if account.is_logged_in else "logged_in: False"
            lines.append(f"{i}. {account.account_id} (role: {account.role}, {status})")
            lines.append(f"   Task: {account.login_task_description}")

        lines.append("- unauthenticated (no credentials)")

        return "\n".join(lines)

    def save_accounts(self):
        """Save account information to JSON"""
        self.store_path.parent.mkdir(parents=True, exist_ok=True)

        data = []
        for account in self.accounts:
            data.append({
                "account_id": account.account_id,
                "login_task_description": account.login_task_description,
                "role": account.role,
                "is_logged_in": account.is_logged_in,
                "credentials": account.credentials,
                "login_url": account.login_url,
                "created_at": account.created_at,
                "has_driver": account.has_driver  # Save driver flag
            })

        with open(self.store_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

    def _load_accounts(self):
        """Load account information from JSON"""
        if not self.store_path.exists():
            return

        try:
            with open(self.store_path, 'r', encoding='utf-8') as f:
                data = json.load(f)

            for item in data:
                account = Account(
                    account_id=item["account_id"],
                    login_task_description=item["login_task_description"],
                    role=item.get("role", "user"),
                    is_logged_in=item.get("is_logged_in", False),
                    credentials=item.get("credentials", {}),
                    login_url=item.get("login_url"),
                    created_at=item.get("created_at", time.time()),
                    has_driver=item.get("has_driver", False)  # Load driver flag
                )
                self.accounts.append(account)

        except Exception as e:
            print(f"[AccountManager] Warning: Failed to load accounts: {e}")







